settings:
  title: 'Seranor Status Page'
  url: 'https://status.seranor.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: seranor-com # unique identifier
    name: seranor.com
    description: '主站' # default=empty
    url: 'https://seranor.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: docker-seranor-com
    name: docker.seranor.com
    description: 'Docker反向代理'
    url: 'https://docker.seranor.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: chat-seranor-com
    name: chat.seranor.com
    description: 'Chat Web访问'
    url: 'https://chat.seranor.com/'
    method: GET
    expectStatus: 200

  - id: edgetunnel-seranor-com
    name: edgetunnel.seranor.com
    description: '白嫖cloudflare的隧道'
    url: 'https://edgetunnel.seranor.com/576c1cce-a2fb-4af8-bf48-94982b8dbb7c'
    method: GET
    expectStatus: 200
